### PR TITLE
Fix delta_time being 0 resulting in incorrect simulation

### LINKED ISSUE #659: delta_time being 0 results in incorrect simulation
context: https://github.com/dimforge/bevy_rapier/issues/535

## Reproduction steps

- create a revolute joint in impulse joints
- run a simulation step with 0 delta time
- 💥 bodies now have NaN translation/rotation.

### PR DESCRIPTION
**Pull request by Vrixyz**
Fixes #659.

Bug introduced by https://github.com/dimforge/rapier/pull/635.

Disclaimer: I am **NOT** confident about the correction, but I'm confident it's the correct place to fix :).

### CODE REVIEW

File: src/dynamics/integration_parameters.rs [hunk 1]
```diff
@@ -221,7 +221,11 @@ impl IntegrationParameters {
     pub fn joint_cfm_coeff(&self) -> Real {
         // Compute CFM assuming a critically damped spring multiplied by the damping ratio.
         // The logic is similar to `Self::cfm_factor`.
-        let inv_erp_minus_one = 1.0 / self.joint_erp() - 1.0;
+        let inv_erp_minus_one = if self.joint_erp() == 0.0 {
+            0.0
```
Comment (Vrixyz) [inline src/dynamics/integration_parameters.rs:225]: `1.0` or `0.0` ?

File: src/dynamics/integration_parameters.rs [hunk 2]
```diff
@@ -221,7 +221,11 @@ impl IntegrationParameters {
     pub fn joint_cfm_coeff(&self) -> Real {
         // Compute CFM assuming a critically damped spring multiplied by the damping ratio.
         // The logic is similar to `Self::cfm_factor`.
```
Comment (Vrixyz) [inline src/dynamics/integration_parameters.rs:223]: should a similar correction be applied to `cfm_factor` ?

Comment (sebcrozet) [reply src/dynamics/integration_parameters.rs:227]: Yes

File: src/dynamics/rigid_body_set.rs [hunk 3]
```diff
@@ -23,7 +23,7 @@ impl BodyPair {
 }
 
 #[cfg_attr(feature = "serde-serialize", derive(Serialize, Deserialize))]
-#[derive(Clone, Default)]
+#[derive(Clone, Default, Debug)]
```
Comment (Vrixyz) [inline src/dynamics/rigid_body_set.rs:26]: irrelevant but 🤷 ; let me know if you prefer it out of the PR.

File: src/pipeline/physics_pipeline.rs [hunk 4]
```diff
@@ -937,4 +939,68 @@ mod test {
...
+        assert!(translation.y.is_finite());
+        #[cfg(feature = "dim2")]
+        assert!(rotation.is_finite());
+        #[cfg(feature = "dim3")]
+        (|| {
+            assert!(translation.z.is_finite());
+            let rotation = rotation.scaled_axis();
+            assert!(rotation.x.is_finite());
+            assert!(rotation.y.is_finite());
+            assert!(rotation.z.is_finite());
```
Comment (Vrixyz) [inline src/pipeline/physics_pipeline.rs:1003]: isn't there a util function to check those in a better way ?

File: src/dynamics/integration_parameters.rs (hunk 2 above)
Comment (Vrixyz) [reply src/dynamics/integration_parameters.rs:227]: also, the correct function referred to is probably `contact_cfm_factor` ?

File: src/pipeline/physics_pipeline.rs [hunk 5]
```diff
@@ -937,4 +939,68 @@ mod test {
...
+            &(),
+        );
+        let translation = bodies.get(h_dynamic).unwrap().translation();
+        let rotation = bodies.get(h_dynamic).unwrap().rotation();
+        assert!(translation.x.is_finite());
+        assert!(translation.y.is_finite());
+        #[cfg(feature = "dim2")]
+        assert!(rotation.is_finite());
+        #[cfg(feature = "dim3")]
+        (|| {
```
Comment (sebcrozet) [inline src/pipeline/physics_pipeline.rs:998]: Why is that a closure that gets immediately called instead of just a scope?

File: src/pipeline/physics_pipeline.rs (hunk 4 above)
Comment (sebcrozet) [reply src/pipeline/physics_pipeline.rs:1003]: No. But instead of testing the `scaled_axis()` you should test the quaternion `i,j,k,w` components directly.

File: src/pipeline/physics_pipeline.rs (hunk 5 above)
Comment (Vrixyz) [reply src/pipeline/physics_pipeline.rs]: I was persuaded I couldn't use those attributes were allowed on a scope only on nightly, but it seems that I'm wrong, thanks! fixed 👍

File: src/dynamics/integration_parameters.rs [hunk 6]
```diff
@@ -220,8 +225,12 @@ impl IntegrationParameters {
     /// [`Self::joint_damping_ratio`] and the substep length.
     pub fn joint_cfm_coeff(&self) -> Real {
         // Compute CFM assuming a critically damped spring multiplied by the damping ratio.
-        // The logic is similar to `Self::cfm_factor`.
-        let inv_erp_minus_one = 1.0 / self.joint_erp() - 1.0;
+        // The logic is similar to `Self::contact_cfm_factor`.
```
Comment (Vrixyz) [inline src/dynamics/integration_parameters.rs:228]: I changed the function name, I think that's more accurate ?

File: CHANGELOG.md [hunk 7]
```diff
@@ -1,3 +1,9 @@
+## Unreleased
+
+### Fix
+
+- Fix `NaN` values appearin in bodies translation and rotation after a simulation step with a delta time equal to 0 ([#660](https://github.com/dimforge/rapier/pull/660)).
```
Comment (sebcrozet) [inline CHANGELOG.md:5]:
```suggestion
- Fix `NaN` values appearing in bodies translation and rotation after a simulation step with a delta time equal to 0 ([#660](https://github.com/dimforge/rapier/pull/660)).
```

File: src/dynamics/rigid_body_set.rs (hunk 3 above)
Comment (sebcrozet) [reply src/dynamics/rigid_body_set.rs:26]: That’s fine.

File: src/pipeline/physics_pipeline.rs [hunk 8]
```diff
@@ -937,4 +939,68 @@ mod test {
...
+        let rb = RigidBodyBuilder::fixed().additional_mass(1.0).build();
+        let h = bodies.insert(rb.clone());
+        let rb_dynamic = RigidBodyBuilder::dynamic().additional_mass(1.0).build();
+        let h_dynamic = bodies.insert(rb_dynamic.clone());
+
+        // Add joint
+        #[cfg(feature = "dim2")]
+        let joint = RevoluteJointBuilder::new()
+            .local_anchor1(point![0.0, 1.0].into())
+            .local_anchor2(point![0.0, -3.0].into());
```
Comment (sebcrozet) [inline src/pipeline/physics_pipeline.rs:965]: What is the `.into()` for?

File: src/pipeline/physics_pipeline.rs [hunk 9]
```diff
@@ -937,4 +939,68 @@ mod test {
...
+        #[cfg(feature = "dim3")]
+        let joint = RevoluteJointBuilder::new(Vector::z_axis())
+            .local_anchor1(point![0.0, 1.0, 0.0].into())
+            .local_anchor2(point![0.0, -3.0, 0.0].into());
```
Comment (sebcrozet) [inline src/pipeline/physics_pipeline.rs:969]: What is the `.into()` for?

File: src/pipeline/physics_pipeline.rs [hunk 10]
```diff
@@ -937,4 +939,68 @@ mod test {
...
+        impulse_joints.insert(h, h_dynamic, joint, true);
+
+        let mut parameters = IntegrationParameters::default();
+        parameters.dt = 0f32.into();
```
Comment (sebcrozet) [inline src/pipeline/physics_pipeline.rs:973]: Why `.into()`? Could this just be `parameters.dt = 0.0;`?

File: src/pipeline/physics_pipeline.rs [hunk 11]
```diff
@@ -937,4 +939,68 @@ mod test {
...
+            &mut colliders,
+            &mut impulse_joints,
+            &mut multibody_joints,
+            &mut CCDSolver::new(),
+            None,
+            &(),
+            &(),
+        );
+        let translation = bodies.get(h_dynamic).unwrap().translation();
+        let rotation = bodies.get(h_dynamic).unwrap().rotation();
```
Comment (sebcrozet) [inline src/pipeline/physics_pipeline.rs:992]:
```suggestion
        let translation = bodies[h_dynamic].translation();
        let rotation = bodies[h_dynamic].rotation();
```

File: src/pipeline/physics_pipeline.rs (hunk 8 above)
Comment (Vrixyz) [reply src/pipeline/physics_pipeline.rs:965]: for transforming into dimension3 I believe ? or a leftover from f32 / f64 🤔  : I'll double check.

**Comment by sebcrozet** [comment]
Thanks!
